# 종류 별로 가장 큰 물고기의 ID, 물고기 이름, 길이

with MaxFinsh AS (
SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
FROM FISH_INFO f
GROUP BY FISH_TYPE
)

SELECT fi.ID, FISH_NAME, f.LENGTH
FROM FISH_INFO fi
JOIN MaxFinsh f ON f.FISH_TYPE = fi.FISH_TYPE AND f.LENGTH = fi.LENGTH
JOIN FISH_NAME_INFO fn ON fi.FISH_TYPE = fn.FISH_TYPE
