SELECT TITLE, bd.BOARD_ID, rp.REPLY_ID, rp.WRITER_ID, rp.CONTENTS, DATE_FORMAT(rp.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD bd
JOIN USED_GOODS_REPLY rp
on bd.BOARD_ID = rp.BOARD_ID
WHERE YEAR(bd.CREATED_DATE) = 2022 AND MONTH(bd.CREATED_DATE) = 10
ORDER BY rp.CREATED_DATE ASC, TITLE ASC
