# 생일이 3월인 여성 회원의 ID, 이름, 성별, 생년월일

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d")
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3 AND GENDER = 'W' AND NOT TLNO IS NULL
ORDER BY MEMBER_ID ASC
