SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
    ol.PRODUCT_ID,
    ol.USER_ID,
    ol.SALES_AMOUNT
FROM ONLINE_SALE ol
WHERE ol.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

UNION 

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
    ofl.PRODUCT_ID,
    NULL AS USER_ID,
    ofl.SALES_AMOUNT
FROM OFFLINE_SALE ofl
WHERE ofl.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'  
order by SALES_DATE, PRODUCT_ID, USER_ID
