SELECT ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES, ri.ADDRESS, ROUND(AVG(rv.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO ri
join REST_REVIEW rv on ri.REST_ID = rv.REST_ID
where ri.ADDRESS like ("서울%")
group by REST_ID
order by SCORE DESC, FAVORITES DESC
