-- 있었는데요 없었습니다
-- https://programmers.co.kr/learn/courses/30/lessons/59043

SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS
LEFT OUTER JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME ASC
