-- 오랜기간 보호한 동물(1)
-- https://programmers.co.kr/learn/courses/30/lessons/59044

SELECT INS.NAME, INS.DATETIME
FROM ANIMAL_INS INS
LEFT OUTER JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY OUTS.DATETIME - INS.DATETIME, INS.DATETIME ASC
LIMIT 3
